### ISSUE TITLE
Facing issue while running dehazetest.py

### ISSUE THREAD

**Issue by DangLienMinh** [hezhangsprinter/NTIRE-2018-Dehazing-Challenge#1]
Hi,

While I am running dehazetest.py. This error occurred, could you give me some advice?

`user01@digits-1:/data2/HEHAZE_OUTDOOR_2018/Outdoor$ python dehazetest.py --dataroot ./sample/outdoortest2 --valDataroo ./sample/outdoortest2 --netG ./pretrained-model/netG_epoch_7500.pth

Namespace(batchSize=1, dataroot='./sample/outdoortest2', dataset='pix2pix', display=5, evalIter=500, exp='sample', imageSize=1024, inputChannelSize=3, lambdaGAN=0.01, lambdaIMG=1, ndf=64, netD='', netG='./pretrained-model/netG_epoch_7500.pth', ngf=64, niter=400, originalSize=1024, outputChannelSize=3, poolSize=50, valBatchSize=1, valDataroot='./sample/outdoortest2', workers=1)
Random Seed:  3693
./pretrained-model/netG_epoch_7500.pth
Traceback (most recent call last):
  File "dehazetest.py", line 112, in <module>
    netG.load_state_dict(state_dict)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
KeyError: 'unexpected key "dense_block1.denselayer1.norm.1.weight" in state_dict'
`

**Comment by hezhangsprinter** [comment]
HI,
    You can have a try installing pytorch with 0.3x rather than the latest 0.4 version. 
https://pytorch.org/previous-versions/

**Comment by agadav** [comment]
Hello, I am facing the same problem:

python dehazetest.py --dataroot ./sample/outdoortest2 --valDataroo ./sample/outdoortest2 --netG ./pretrained-model/netG_epoch_7500.pth
Namespace(batchSize=1, dataroot='./sample/outdoortest2', dataset='pix2pix', display=5, evalIter=500, exp='sample', imageSize=1024, inputChannelSize=3, lambdaGAN=0.01, lambdaIMG=1, ndf=64, netD='', netG='./pretrained-model/netG_epoch_7500.pth', ngf=64, niter=400, originalSize=1024, outputChannelSize=3, poolSize=50, valBatchSize=1, valDataroot='./sample/outdoortest2', workers=1)
Random Seed:  211
Traceback (most recent call last):
  File "dehazetest.py", line 109, in <module>
    netG.load_state_dict(torch.load(opt.netG, map_location=lambda storage, loc: storage))
  File "/home/agapi/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "dense_block1.denselayer1.norm.1.weight" in state_dict

I am using pytorch 0.3.1. Do you have any advice, how to solve this?

Thanks in advance!
